name: Firebase CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Print Firebase Config
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}"

      - name: Run JavaScript script
        run: |
          echo "const firebaseConfig = ${JSON.stringify(process.env.FIREBASE_CONFIG)};" > script.js
          echo "console.log(firebaseConfig);" >> script.js
          node script.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
