name: Firebase CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Inject secrets and build
        run: |
          echo "FIREBASE_CONFIG=${{ secrets.FIREBASE_CONFIG }}" >> .env
          npm run build
